# Generated by Django 5.2.7 on 2025-10-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente', serialize=False, to='gestionApp.persona')),
                ('Edad', models.PositiveSmallIntegerField(help_text='Edad entre 12 y 60 años')),
                ('Estado_civil', models.CharField(choices=[('SOLTERA', 'Soltera'), ('CASADA', 'Casada'), ('CONVIVIENTE', 'Conviviente'), ('DIVORCIADA', 'Divorciada'), ('VIUDA', 'Viuda')], max_length=20)),
                ('Previcion', models.CharField(choices=[('FONASA_A', 'FONASA A'), ('FONASA_B', 'FONASA B'), ('FONASA_C', 'FONASA C'), ('FONASA_D', 'FONASA D'), ('ISAPRE', 'Isapre'), ('PARTICULAR', 'Particular')], max_length=20, verbose_name='Previsión')),
                ('Acompañante', models.CharField(blank=True, max_length=120)),
                ('Contacto_emergencia', models.CharField(blank=True, max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='IngresoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('numero_ficha', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Número de ficha')),
                ('motivo_consulta', models.TextField()),
                ('edad_gestacional_sem', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('derivacion', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='matronaApp.paciente')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SeleccionPatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=180)),
                ('codigo_cie_10', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patologias_asignadas', to='matronaApp.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('paciente', 'catalogo_id')},
            },
        ),
    ]
