# Generated by Django 5.2.7 on 2025-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la patología', max_length=200, verbose_name='Nombre de la patología')),
                ('codigo_cie_10', models.CharField(choices=[('A09 - Enfermedades diarreicas de probable origen infeccioso', 'A09 - Enfermedades diarreicas de probable origen infeccioso'), ('E11 - Diabetes mellitus tipo 2', 'E11 - Diabetes mellitus tipo 2'), ('I10 - Hipertensión esencial (primaria)', 'I10 - Hipertensión esencial (primaria)'), ('J00 - Resfriado común', 'J00 - Resfriado común'), ('F32 - Episodio depresivo mayor, episodio único', 'F32 - Episodio depresivo mayor, episodio único'), ('K21 - Enfermedad por reflujo gastroesofágico (ERGE)', 'K21 - Enfermedad por reflujo gastroesofágico (ERGE)'), ('M54 - Dolor en la columna vertebral', 'M54 - Dolor en la columna vertebral'), ('N39 - Infección del tracto urinario no especificada', 'N39 - Infección del tracto urinario no especificada')], help_text='Código CIE-10 de la patología', max_length=100, verbose_name='Código CIE-10')),
                ('descripcion', models.TextField(help_text='Breve descripción de la patología', verbose_name='Descripción de la patología')),
                ('nivel_de_riesgo', models.CharField(choices=[('CV_Bajo', 'Cardiovascular (CV) - Bajo'), ('MB_Bajo', 'Metabólica (MB) - Bajo'), ('CV_Medio', 'Cardiovascular (CV) - Medio'), ('MB_Medio', 'Metabólica (MB) - Medio'), ('RR_Alto', 'Respiratoria (RR) - Alto'), ('NN_Alto', 'Neurológica (NN) - Alto')], help_text='Nivel de riesgo de la patología (Ej. Cardiovascular, Respiratoria)', max_length=50, verbose_name='Nivel de riesgo')),
                ('protocologo_de_segimiento', models.TextField(help_text='Protocolo de seguimiento de la patología', verbose_name='Protocolo de seguimiento')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', help_text='Estado de la patología (Activo/Inactivo)', max_length=10, verbose_name='Estado de la patología')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Patología',
                'verbose_name_plural': 'Registros de Patologías',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
