# Generated by Django 5.2.7 on 2025-10-10 02:24

import django.db.models.deletion
import utilidad.rut_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(help_text='Ingrese RUT de la persona (formato: 12345678-9)', max_length=100, unique=True, validators=[utilidad.rut_validator._validar_rut], verbose_name='RUT')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100, verbose_name='Sexo')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Telefono', models.CharField(blank=True, max_length=100, verbose_name='Telefono')),
                ('Direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('Email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Obstetricia General', 'Obstetricia General'), ('Ginecología', 'Ginecología'), ('Medicina Materno Fetal', 'Medicina Materno Fetal')], max_length=100)),
                ('Registro_medico', models.CharField(max_length=100, unique=True)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Matrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Atención del Parto', 'Atención del Parto'), ('Control Prenatal', 'Control Prenatal'), ('Neonatología', 'Neonatología')], max_length=100)),
                ('Registro_medico', models.CharField(max_length=100, unique=True)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(choices=[('Preparto', 'Preparto'), ('Parto', 'Parto'), ('Puerperio', 'Puerperio'), ('Neonatología', 'Neonatología')], max_length=100)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Certificaciones', models.CharField(choices=[('SVB', 'Soporte Vital Básico'), ('Parto Normal', 'Certificación en Parto Normal')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
    ]
